---
# Per environment values which override defaults in bh-example-frontend-app-dev/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: bh-example-frontend-app-dev-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://bh-example-frontend-app-dev-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev